/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.diansetiyadi.APP;

import com.diansetiyadi.DAO.TarifFileDAO;
import com.diansetiyadi.Model.DataPengirimanPaket;
import com.diansetiyadi.Model.Insurance;
import com.diansetiyadi.Model.Pengirim;
import com.diansetiyadi.Model.Tarif;
import com.diansetiyadi.Model.provinsiKota;
import com.diansetiyadi.Model.resiGenerator;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Tarif tarif = new Tarif();
    Pengirim pengirim = new Pengirim();
    Insurance insurance = new Insurance();
    DataPengirimanPaket dpk = new DataPengirimanPaket();
    TarifFileDAO tfd = new TarifFileDAO();
    provinsiKota provinsikota = new provinsiKota();
    //provinsiKota[] provinsikotas;

    public GUI() {
        initComponents();
        // tfd.findKota();
        tfd.findTarif();
        tarif.setPengirim(pengirim);
        insurance.setDpk(dpk);
        tarif.setInsurance(insurance);

        textAsuransiPercent.setText("" + insurance.getInsurancepercent());
        setHargaBarangInvisible();
        setNamaBarangInvisible();
        defaultMenu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    DecimalFormat df = new DecimalFormat("'Rp'###,###.##");
    SimpleDateFormat dateformat = new SimpleDateFormat("dd MMM yyyy");

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAsuransi = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textProvinsiPengirim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textNamaPengirim = new javax.swing.JTextField();
        textKotaPengirim = new javax.swing.JTextField();
        textKodePosPengirim = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaAlamatPengirim = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        textTelephonePengirim = new javax.swing.JTextField();
        TOP_PANEL = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textProvinsiPenerima = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        textKotaPenerima = new javax.swing.JTextField();
        textNamaPenerima = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        textKodePosPenerima = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaAlamatPenerima = new javax.swing.JTextArea();
        textTelephonePenerima = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelDataPengiriman = new javax.swing.JPanel();
        textNomorPaket = new javax.swing.JTextField();
        textNamaBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelHargaBarang = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboJenisBarang = new javax.swing.JComboBox<>();
        textBeratBarang1 = new javax.swing.JTextField();
        textDimensiPanjang = new javax.swing.JTextField();
        textDimensiTinggi = new javax.swing.JTextField();
        textDimensiLebar = new javax.swing.JTextField();
        comboJenisLayanan = new javax.swing.JComboBox<>();
        rbtnSetuju = new javax.swing.JRadioButton();
        rbtnTidak = new javax.swing.JRadioButton();
        textHargaBarang = new javax.swing.JTextField();
        comboPembayaran = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        textAsuransiPercent = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelNamaBarang = new javax.swing.JLabel();
        textTujuanPengirim = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        buttonCalculate = new javax.swing.JButton();
        dateTanggalPengiriman = new com.toedter.calendar.JDateChooser();
        panelDetailPengiriman = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        textJumlah = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDetailPembelian = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        buttonClear = new javax.swing.JButton();
        buttonSubmit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuNewDelivery = new javax.swing.JMenu();
        menuItemNew = new javax.swing.JMenuItem();
        menuItemSimulasiHarga = new javax.swing.JMenuItem();
        menuItemResetMode = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuItemPrint = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuItemThank = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pengirim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel1.setText("Nama");

        jLabel2.setText("Kota");

        jLabel18.setText("Kode Pos");

        jLabel19.setText("Provinsi");

        textKotaPengirim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textKotaPengirimFocusGained(evt);
            }
        });
        textKotaPengirim.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textKotaPengirimInputMethodTextChanged(evt);
            }
        });
        textKotaPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKotaPengirimActionPerformed(evt);
            }
        });

        jLabel24.setText("Tekan Enter Jika Sudah Input");

        jLabel20.setText("Alamat");

        textAreaAlamatPengirim.setColumns(20);
        textAreaAlamatPengirim.setRows(5);
        jScrollPane3.setViewportView(textAreaAlamatPengirim);

        jLabel22.setText("Telephone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(textNamaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textProvinsiPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textKotaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textKodePosPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(0, 33, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(textTelephonePengirim)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNamaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textKotaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(textTelephonePengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(textKodePosPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(textProvinsiPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        TOP_PANEL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("APLIKASI PENGIRIMAN BARANG");

        javax.swing.GroupLayout TOP_PANELLayout = new javax.swing.GroupLayout(TOP_PANEL);
        TOP_PANEL.setLayout(TOP_PANELLayout);
        TOP_PANELLayout.setHorizontalGroup(
            TOP_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TOP_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TOP_PANELLayout.setVerticalGroup(
            TOP_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TOP_PANELLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Penerima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel25.setText("Nama");

        textKotaPenerima.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textKotaPenerimaFocusGained(evt);
            }
        });
        textKotaPenerima.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textKotaPenerimaInputMethodTextChanged(evt);
            }
        });
        textKotaPenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKotaPenerimaActionPerformed(evt);
            }
        });

        jLabel26.setText("Kota");

        jLabel27.setText("Kode Pos");

        jLabel28.setText("Provinsi");

        jLabel36.setText("Tekan Enter Jika Sudah Input");

        jLabel21.setText("Alamat");

        textAreaAlamatPenerima.setColumns(20);
        textAreaAlamatPenerima.setRows(5);
        jScrollPane4.setViewportView(textAreaAlamatPenerima);

        jLabel29.setText("Telephone");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textProvinsiPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(textKotaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel36))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(textKodePosPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(textTelephonePenerima, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(textNamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(textKotaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(textTelephonePenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(textKodePosPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textProvinsiPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1024, 800));

        panelDataPengiriman.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pengiriman", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        panelDataPengiriman.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textNomorPaket.setEditable(false);
        textNomorPaket.setBackground(new java.awt.Color(102, 102, 102));
        textNomorPaket.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textNomorPaket.setForeground(new java.awt.Color(255, 0, 0));
        panelDataPengiriman.add(textNomorPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 37, 151, -1));

        textNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaBarangActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(textNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 135, 137, -1));

        jLabel3.setText("Nomor Paket");
        panelDataPengiriman.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 40, -1, -1));

        jLabel4.setText("Kota Tujuan");
        panelDataPengiriman.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 78, -1, -1));

        jLabel5.setText("Jenis Barang");
        panelDataPengiriman.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 109, -1, -1));

        jLabel6.setText("Berat Barang");
        panelDataPengiriman.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 169, -1, -1));

        jLabel7.setText("Tanggal Kirim");
        panelDataPengiriman.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 200, -1, -1));

        jLabel8.setText("Dimensi");
        panelDataPengiriman.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 238, -1, -1));

        jLabel9.setText("Panjang");
        panelDataPengiriman.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 238, -1, -1));

        jLabel10.setText("Tinggi");
        panelDataPengiriman.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 269, -1, -1));

        jLabel11.setText("Lebar");
        panelDataPengiriman.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 303, -1, -1));

        jLabel12.setText("Jenis Layanan");
        panelDataPengiriman.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 341, -1, -1));

        jLabel13.setText("Asuransi 10%");
        panelDataPengiriman.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 380, -1, -1));

        labelHargaBarang.setText("Harga Barang");
        panelDataPengiriman.add(labelHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 420, -1, -1));

        jLabel15.setText("Pembayaran");
        panelDataPengiriman.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 458, -1, -1));

        comboJenisBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dokumen", "Elektronik", "Makanan", "DLL" }));
        comboJenisBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboJenisBarangItemStateChanged(evt);
            }
        });
        panelDataPengiriman.add(comboJenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 106, 148, -1));

        textBeratBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBeratBarang1ActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(textBeratBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 166, 34, -1));

        textDimensiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDimensiPanjangActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(textDimensiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 235, 45, -1));

        textDimensiTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDimensiTinggiActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(textDimensiTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 266, 45, -1));

        textDimensiLebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDimensiLebarActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(textDimensiLebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 300, 45, -1));

        comboJenisLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Kilat", "SDS", "ONS", "HDS" }));
        panelDataPengiriman.add(comboJenisLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 338, 161, -1));

        buttonGroupAsuransi.add(rbtnSetuju);
        rbtnSetuju.setText("Setuju");
        rbtnSetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSetujuActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(rbtnSetuju, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 376, -1, -1));

        buttonGroupAsuransi.add(rbtnTidak);
        rbtnTidak.setText("Tidak");
        rbtnTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTidakActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(rbtnTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 376, -1, -1));

        textHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHargaBarangActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(textHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 417, 162, -1));

        comboPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit", "Credit Card" }));
        panelDataPengiriman.add(comboPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 455, 117, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelDataPengiriman.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 509, -1, -1));
        panelDataPengiriman.add(textAsuransiPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 376, 87, -1));

        jLabel17.setText("KG");
        panelDataPengiriman.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 169, -1, -1));

        labelNamaBarang.setText("Nama Barang");
        panelDataPengiriman.add(labelNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 138, -1, -1));

        textTujuanPengirim.setEditable(false);
        textTujuanPengirim.setBackground(new java.awt.Color(102, 102, 102));
        textTujuanPengirim.setForeground(new java.awt.Color(255, 255, 255));
        textTujuanPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTujuanPengirimActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(textTujuanPengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 75, 151, -1));

        jLabel14.setText("CM");
        panelDataPengiriman.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 238, -1, -1));

        jLabel23.setText("CM");
        panelDataPengiriman.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 269, -1, -1));

        jLabel34.setText("CM");
        panelDataPengiriman.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 303, -1, -1));

        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });
        panelDataPengiriman.add(buttonCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        dateTanggalPengiriman.setDateFormatString("dd MMM yyyy");
        panelDataPengiriman.add(dateTanggalPengiriman, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, -1));

        jScrollPane1.setViewportView(panelDataPengiriman);

        panelDetailPengiriman.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Harga Pengiriman", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        textJumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textJumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textAreaDetailPembelian.setEditable(false);
        textAreaDetailPembelian.setBackground(new java.awt.Color(102, 102, 102));
        textAreaDetailPembelian.setColumns(20);
        textAreaDetailPembelian.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textAreaDetailPembelian.setForeground(new java.awt.Color(255, 255, 255));
        textAreaDetailPembelian.setRows(5);
        textAreaDetailPembelian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(textAreaDetailPembelian);

        javax.swing.GroupLayout panelDetailPengirimanLayout = new javax.swing.GroupLayout(panelDetailPengiriman);
        panelDetailPengiriman.setLayout(panelDetailPengirimanLayout);
        panelDetailPengirimanLayout.setHorizontalGroup(
            panelDetailPengirimanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailPengirimanLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelDetailPengirimanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDetailPengirimanLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDetailPengirimanLayout.setVerticalGroup(
            panelDetailPengirimanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailPengirimanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/diansetiyadi/asset/logo tugas.png"))); // NOI18N

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonClear)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClear)
                    .addComponent(buttonSubmit))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        menuNewDelivery.setText("File");
        menuNewDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewDeliveryActionPerformed(evt);
            }
        });

        menuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemNew.setText("New Delivery");
        menuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewActionPerformed(evt);
            }
        });
        menuNewDelivery.add(menuItemNew);

        menuItemSimulasiHarga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSimulasiHarga.setText("Simulasi Harga");
        menuItemSimulasiHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSimulasiHargaActionPerformed(evt);
            }
        });
        menuNewDelivery.add(menuItemSimulasiHarga);

        menuItemResetMode.setText("Reset Mode");
        menuItemResetMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemResetModeActionPerformed(evt);
            }
        });
        menuNewDelivery.add(menuItemResetMode);

        jMenuItem1.setText("Delivery");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuNewDelivery.add(jMenuItem1);

        jMenuItem3.setText("Open");
        menuNewDelivery.add(jMenuItem3);

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuNewDelivery.add(menuItemExit);

        jMenuBar1.add(menuNewDelivery);

        menuAdmin.setText("Master Data");
        menuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Admin");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAdmin.add(jMenuItem2);

        menuItemPrint.setText("Print");
        menuItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrintActionPerformed(evt);
            }
        });
        menuAdmin.add(menuItemPrint);

        jMenuBar1.add(menuAdmin);

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });

        menuItemThank.setText("Thank For");
        menuItemThank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThankActionPerformed(evt);
            }
        });
        menuAbout.add(menuItemThank);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(panelDetailPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(TOP_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TOP_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelDetailPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaBarangActionPerformed

    private void textBeratBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBeratBarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBeratBarang1ActionPerformed

    private void textDimensiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDimensiPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDimensiPanjangActionPerformed

    private void textDimensiTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDimensiTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDimensiTinggiActionPerformed

    private void textDimensiLebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDimensiLebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDimensiLebarActionPerformed

    private void textHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHargaBarangActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:

        fillButtonSubmit();
        isAsuransi();
        isPelayanan();
        setResultPengiriman();

    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        actionClearButtonSubmit();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void rbtnSetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSetujuActionPerformed
        // TODO add your handling code here:
        //isAsuransi();
        isAsuransiVisible();
    }//GEN-LAST:event_rbtnSetujuActionPerformed

    private void rbtnTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTidakActionPerformed
        // TODO add your handling code here:
        //  isAsuransi();
        isAsuransiVisible();
    }//GEN-LAST:event_rbtnTidakActionPerformed

    private void textTujuanPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTujuanPengirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTujuanPengirimActionPerformed

    private void comboJenisBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboJenisBarangItemStateChanged
        // TODO add your handling code here:
        setNamaBarangVisiblle();
        if (comboJenisBarang.getSelectedItem().equals("None")) {
            setNamaBarangInvisible();
        } else {
            setNamaBarangVisiblle();
        }
    }//GEN-LAST:event_comboJenisBarangItemStateChanged

    private void textKotaPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKotaPengirimActionPerformed
        // TODO add your handling code here:
        setProvinsiKotaPengirim();
    }//GEN-LAST:event_textKotaPengirimActionPerformed

    private void textKotaPengirimInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textKotaPengirimInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_textKotaPengirimInputMethodTextChanged

    private void textKotaPengirimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textKotaPengirimFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_textKotaPengirimFocusGained

    private void textKotaPenerimaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textKotaPenerimaInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_textKotaPenerimaInputMethodTextChanged

    private void textKotaPenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKotaPenerimaActionPerformed
        // TODO add your handling code here:
        setProvinsiKotaPenerima();
    }//GEN-LAST:event_textKotaPenerimaActionPerformed

    private void textKotaPenerimaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textKotaPenerimaFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_textKotaPenerimaFocusGained

    private void menuNewDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewDeliveryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuNewDeliveryActionPerformed

    private void menuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewActionPerformed
        // TODO add your handling code here:
        setNewDeliveryVisible();


    }//GEN-LAST:event_menuItemNewActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuAdminActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Soon");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        // TODO add your handling code here:
        fillButtonCalculate();
        isAsuransiCalculate();
        isPelayananButtonCalculate();
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void menuItemSimulasiHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSimulasiHargaActionPerformed
        // TODO add your handling code here:
        setSimulasiHargaMenuVisible();


    }//GEN-LAST:event_menuItemSimulasiHargaActionPerformed

    private void menuItemResetModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemResetModeActionPerformed
        // TODO add your handling code here:
        defaultMenu();
    }//GEN-LAST:event_menuItemResetModeActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuItemThankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThankActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Thank My Trainer");
    }//GEN-LAST:event_menuItemThankActionPerformed

    private void menuItemPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrintActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Soon");
    }//GEN-LAST:event_menuItemPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public void defaultMenu() {
        panelDetailPengiriman.setVisible(false);
        rbtnTidak.setSelected(true);
        textAsuransiPercent.setVisible(false);
        buttonCalculate.setVisible(false);
        buttonSubmit.setEnabled(false);
        buttonClear.setEnabled(false);
        textNamaPenerima.setEnabled(false);
        textNamaPengirim.setEnabled(false);
        textKotaPenerima.setEnabled(false);
        textKotaPengirim.setEnabled(false);
        textKodePosPenerima.setEnabled(false);
        textKodePosPengirim.setEnabled(false);
        textTelephonePenerima.setEnabled(false);
        textTelephonePengirim.setEnabled(false);
        textBeratBarang1.setEnabled(false);
        comboJenisBarang.setEnabled(false);
        comboPembayaran.setEnabled(false);
        comboJenisLayanan.setEnabled(false);
        textProvinsiPenerima.setEnabled(false);
        textAreaAlamatPengirim.setEnabled(false);
        textProvinsiPengirim.setEnabled(false);
        textAreaAlamatPenerima.setEnabled(false);

        //Panel Data Pengiriman
        //textGroupDimensi Barang
        dateTanggalPengiriman.setEnabled(false);
        textDimensiLebar.setEnabled(false);
        textDimensiPanjang.setEnabled(false);
        textDimensiTinggi.setEnabled(false);

        //buttonGroupAsuransi
        rbtnSetuju.setEnabled(false);
        rbtnTidak.setEnabled(false);
    }

    public void isPelayanan() {

        if (comboJenisLayanan.getSelectedItem().equals("Reguler")) {

            tarif.setOngkirBarang();
            tarif.hargaPaketReguler();
            tarif.setTotalHargaAfterInsurance();
            //  labelAsuransi.setText("" + insurance.calculateInsuranceBarang());
            textJumlah.setText("" + df.format(tarif.getTotalHargaAfterInsurance()));

            dpk.setLamaPengiriman("3 - 4 Hari Pengiriman");

            dpk.setJenisLayanan("Reguler");
            textNomorPaket.setText(resiGenerator.generateResiNumber() + "REG");

        } else if (comboJenisLayanan.getSelectedItem().equals("Kilat")) {
            tarif.hargaPaketKilat();
            tarif.setOngkirBarang();
            tarif.setTotalHargaAfterInsurance();

            textJumlah.setText("" + df.format(tarif.getTotalHargaAfterInsurance()));

            dpk.setLamaPengiriman("1 - 2 Hari Pengiriman");

            dpk.setJenisLayanan("Kilat");

            textNomorPaket.setText(resiGenerator.generateResiNumber() + "KLT");
        } else if (comboJenisLayanan.getSelectedItem().equals("SDS")) {
            tarif.hargaPaketSDS();
            tarif.setOngkirBarang();
            tarif.setTotalHargaAfterInsurance();

            textJumlah.setText("" + df.format(tarif.getTotalHargaAfterInsurance()));

            dpk.setLamaPengiriman("Sampai Pada Hari Yang Sama");

            dpk.setJenisLayanan("SDS");

            textNomorPaket.setText(resiGenerator.generateResiNumber() + "SDS");
        } else if (comboJenisLayanan.getSelectedItem().equals("ONS")) {
            tarif.hargaPaketONS();
            tarif.setOngkirBarang();
            tarif.setTotalHargaAfterInsurance();

            textJumlah.setText("" + df.format(tarif.getTotalHargaAfterInsurance()));

            dpk.setLamaPengiriman("(One Night Service) Sampai Besok Pagi");

            dpk.setJenisLayanan("ONS");

            textNomorPaket.setText(resiGenerator.generateResiNumber() + "ONS");
        } else if (comboJenisLayanan.getSelectedItem().equals("HDS")) {
            tarif.hargaPaketHDS();
            tarif.setOngkirBarang();
            tarif.setTotalHargaAfterInsurance();

            textJumlah.setText("" + df.format(tarif.getTotalHargaAfterInsurance()));

            dpk.setLamaPengiriman("(Holiday Service) Pengiriman Di Hari libur");

            dpk.setJenisLayanan("HDS");

            textNomorPaket.setText(resiGenerator.generateResiNumber() + "HDS");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tujuan Tidak Ditemukan Di System");
        }
    }

    public void isPelayananButtonCalculate() {

        if (comboJenisLayanan.getSelectedItem().equals("Reguler")) {

            tarif.setOngkirBarang();
            tarif.hargaPaketReguler();
            tarif.setTotalHargaAfterInsurance();
            //  labelAsuransi.setText("" + insurance.calculateInsuranceBarang()); untuk Mengecek Asuransi Percent
            JOptionPane.showMessageDialog(rootPane, "Harga Total "
                    + df.format(tarif.getTotalHargaAfterInsurance())
                    + " Asuransi " + "(" + tarif.getInsurance().getInsuranceCetak() + ")");

            JOptionPane.showMessageDialog(comboJenisLayanan, "Dengan Layanan "
                    + comboJenisLayanan.getSelectedItem() + " 3 - 4 Hari Pengiriman");

        } else if (comboJenisLayanan.getSelectedItem().equals("Kilat")) {
            tarif.hargaPaketKilat();
            tarif.setOngkirBarang();
            tarif.setTotalHargaAfterInsurance();

            JOptionPane.showMessageDialog(rootPane, "Harga Total "
                    + df.format(tarif.getTotalHargaAfterInsurance())
                    + " Asuransi " + "(" + tarif.getInsurance().getInsuranceCetak() + ")");

            JOptionPane.showMessageDialog(comboJenisLayanan, "Dengan Layanan "
                    + comboJenisLayanan.getSelectedItem() + " 1 - 2 Hari Pengiriman");
        } else if (comboJenisLayanan.getSelectedItem().equals("SDS")) {
            tarif.hargaPaketSDS();
            tarif.setOngkirBarang();
            tarif.setTotalHargaAfterInsurance();

            JOptionPane.showMessageDialog(rootPane, "Harga Total "
                    + df.format(tarif.getTotalHargaAfterInsurance())
                    + " Asuransi " + "(" + tarif.getInsurance().getInsuranceCetak() + ")");

            JOptionPane.showMessageDialog(comboJenisLayanan, "Dengan Layanan "
                    + comboJenisLayanan.getSelectedItem() + " Sampai Pada Hari Yang Sama");
        } else if (comboJenisLayanan.getSelectedItem().equals("ONS")) {
            tarif.hargaPaketONS();
            tarif.setOngkirBarang();
            tarif.setTotalHargaAfterInsurance();

            JOptionPane.showMessageDialog(rootPane, "Harga Total "
                    + df.format(tarif.getTotalHargaAfterInsurance())
                    + " Asuransi " + "(" + tarif.getInsurance().getInsuranceCetak() + ")");

            JOptionPane.showMessageDialog(comboJenisLayanan, "Dengan Layanan "
                    + comboJenisLayanan.getSelectedItem() + " One Night Service Sampai Besok Pagi");
            tarif.hargaPaketHDS();
            tarif.setOngkirBarang();
            tarif.setTotalHargaAfterInsurance();

            JOptionPane.showMessageDialog(rootPane, "Harga Total "
                    + df.format(tarif.getTotalHargaAfterInsurance())
                    + " Asuransi " + "(" + tarif.getInsurance().getInsuranceCetak() + ")");

            JOptionPane.showMessageDialog(comboJenisLayanan, "Dengan Layanan "
                    + comboJenisLayanan.getSelectedItem() + " Holiday Service Dikirim Pada Hari Libur");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tujuan Tidak Ditemukan Di System");
        }
    }

    public void isAsuransi() {
        if (rbtnSetuju.isSelected()) {

            tarif.setAsuransi(true);
            setHargaBarangVisible(true);

            try {
                dpk.setHargaBarang(Double.parseDouble(textHargaBarang.getText()));
            } catch (NumberFormatException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Mohon Masukan Harga Barang");
            }
            insurance.setInsuranceCetak("YES");
        } else if (rbtnTidak.isSelected()) {

            tarif.setAsuransi(false);
            setHargaBarangVisible(false);

            insurance.setInsuranceCetak("NO");

        }
    }

    public void isAsuransiCalculate() {
        if (rbtnSetuju.isSelected()) {

            tarif.setAsuransi(true);
            setHargaBarangVisible(true);
            dpk.setHargaBarang(Double.parseDouble(textHargaBarang.getText()));
            insurance.setInsuranceCetak("YES");
        } else if (rbtnTidak.isSelected()) {

            tarif.setAsuransi(false);
            setHargaBarangVisible(false);
            insurance.setInsuranceCetak("NO");
        }
    }

    public void isAsuransiVisible() {
        if (rbtnSetuju.isSelected()) {

            setHargaBarangVisible(true);

        } else if (rbtnTidak.isSelected()) {

            setHargaBarangVisible(false);

        }
    }

    public void fillButtonSubmit() {

        try {
            tarif.getPengirim().setBeratBarang(Integer.parseInt(textBeratBarang1.getText()));
        } catch (NumberFormatException a) {
            JOptionPane.showMessageDialog(rootPane, "Masukan Angka Pada Berat Barang");
        }

        try {
            tarif.setKota(textTujuanPengirim.getText());
        } catch (Exception err) {
            JOptionPane.showMessageDialog(rootPane, "Kota Tujuan Tidak Ada Pada System");
        }

        dpk.setNamaBarang(textNamaBarang.getText());
        pengirim.setNama(textNamaPengirim.getText());
        dpk.setPembayaran(comboPembayaran.getSelectedItem().toString());

        try {
            dpk.setTanggalPengiriman(dateTanggalPengiriman.getDate());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Isi Tanggal Pengiriman");
        }

    }

    public void fillButtonCalculate() {

        try {
            tarif.getPengirim().setBeratBarang(Integer.parseInt(textBeratBarang1.getText()));
        } catch (NumberFormatException a) {
            JOptionPane.showMessageDialog(rootPane, "Masukan Angka Pada Berat Barang");
        }

        try {
            tarif.setKota(textTujuanPengirim.getText());
        } catch (Exception err) {
            JOptionPane.showMessageDialog(rootPane, "Kota Tujuan Tidak Ada Pada System");
        }

    }

    public void actionClearButtonSubmit() {
        textBeratBarang1.setText("");
        textJumlah.setText("0");
        textProvinsiPengirim.setText("");
        textHargaBarang.setText("0");
    }

    public void setHargaBarangVisible(Boolean vis) {
        textHargaBarang.setVisible(vis);
        labelHargaBarang.setVisible(vis);
    }

    public void setNamaBarangVisiblle() {
        textNamaBarang.setVisible(true);

        labelNamaBarang.setVisible(true);
    }

    public void setHargaBarangInvisible() {

        textHargaBarang.setVisible(false);

        labelHargaBarang.setVisible(false);
    }

    public void setNamaBarangInvisible() {

        textNamaBarang.setVisible(false);
        labelNamaBarang.setVisible(false);

    }

    public void setSimulasiHargaMenuVisible() {
        if (JOptionPane.showConfirmDialog(null, "Kamu Yakin Ingi Mode Simulasi Harga?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // yes option
            buttonCalculate.setVisible(true);
            panelDetailPengiriman.setVisible(false);
            buttonSubmit.setEnabled(false);
            buttonClear.setEnabled(false);
            textNamaPenerima.setEnabled(true);
            textNamaPengirim.setEnabled(true);
            textKotaPenerima.setEnabled(true);
            textKotaPengirim.setEnabled(true);
            textKodePosPenerima.setEnabled(true);
            textKodePosPengirim.setEnabled(true);
            textTelephonePenerima.setEnabled(true);
            textTelephonePengirim.setEnabled(true);
            textBeratBarang1.setEnabled(true);
            comboJenisBarang.setEnabled(true);
            comboPembayaran.setEnabled(true);
            comboJenisLayanan.setEnabled(true);
            textProvinsiPenerima.setEnabled(true);
            textAreaAlamatPengirim.setEnabled(true);
            textProvinsiPengirim.setEnabled(true);
            textAreaAlamatPenerima.setEnabled(true);

            //Panel Data Pengiriman
            //textGroupDimensi Barang
            dateTanggalPengiriman.setEnabled(true);
            textDimensiLebar.setEnabled(true);
            textDimensiPanjang.setEnabled(true);
            textDimensiTinggi.setEnabled(true);

            //buttonGroupAsuransi
            rbtnSetuju.setEnabled(true);
            rbtnTidak.setEnabled(true);

        } else {
            // no option
            buttonCalculate.setVisible(false);
        }

    }

    public void setNewDeliveryVisible() {
        panelDetailPengiriman.setVisible(true);
        textJumlah.setText("Rp0");
        buttonSubmit.setEnabled(true);
        buttonClear.setEnabled(true);
        textNamaPenerima.setEnabled(true);
        textNamaPengirim.setEnabled(true);
        textKotaPenerima.setEnabled(true);
        textKotaPengirim.setEnabled(true);
        textKodePosPenerima.setEnabled(true);
        textKodePosPengirim.setEnabled(true);
        textTelephonePenerima.setEnabled(true);
        textTelephonePengirim.setEnabled(true);
        textBeratBarang1.setEnabled(true);
        comboJenisBarang.setEnabled(true);
        comboPembayaran.setEnabled(true);
        comboJenisLayanan.setEnabled(true);
        textProvinsiPenerima.setEnabled(true);
        textAreaAlamatPengirim.setEnabled(true);
        textProvinsiPengirim.setEnabled(true);
        textAreaAlamatPenerima.setEnabled(true);

        //Panel Data Pengiriman
        //textGroupDimensi Barang
        dateTanggalPengiriman.setEnabled(true);
        textDimensiLebar.setEnabled(true);
        textDimensiPanjang.setEnabled(true);
        textDimensiTinggi.setEnabled(true);

        //buttonGroupAsuransi
        rbtnSetuju.setEnabled(true);
        rbtnTidak.setEnabled(true);
        
        dateTanggalPengiriman.setDate(Date.from(Instant.now()));

    }

    public void setProvinsiKotaPengirim() {
        if (textKotaPengirim.getText().equalsIgnoreCase("jakarta utara")) {
            textProvinsiPengirim.setText("DKI JAKARTA");
        } else if (textKotaPengirim.getText().equalsIgnoreCase("jakarta selatan")) {
            textProvinsiPengirim.setText("DKI JAKARTA");
        } else if (textKotaPengirim.getText().equalsIgnoreCase("jakarta barat")) {
            textProvinsiPengirim.setText("DKI JAKARTA");
        } else if (textKotaPengirim.getText().equalsIgnoreCase("jakarta timur")) {
            textProvinsiPengirim.setText("DKI JAKARTA");
        } else if (textKotaPengirim.getText().equalsIgnoreCase("")) {
            textProvinsiPengirim.setText("");

        } else {
            JOptionPane.showMessageDialog(textKotaPengirim, "Kota Tidak Ditemukan Di System");
        }
    }

    public void setProvinsiKotaPenerima() {
        if (textKotaPenerima.getText().equalsIgnoreCase("bandung")) {
            textProvinsiPenerima.setText("JAWA BARAT");
            textTujuanPengirim.setText("Bandung");
        } else if (textKotaPenerima.getText().equalsIgnoreCase("surabaya")) {
            textProvinsiPenerima.setText("JAWA TIMUR");
            textTujuanPengirim.setText("Surabaya");
        } else if (textKotaPenerima.getText().equalsIgnoreCase("tasikmalaya")) {
            textProvinsiPenerima.setText("JAWA TENGAH");
            textTujuanPengirim.setText("TasikMalaya");
        } else if (textKotaPenerima.getText().equalsIgnoreCase("yogyakarta")) {
            textProvinsiPenerima.setText("JAWA TENGAH");
            textTujuanPengirim.setText("Yogyakarta");
        } else if (textKotaPenerima.getText().equalsIgnoreCase("medan")) {
            textProvinsiPenerima.setText("SUMATERA UTARA");
            textTujuanPengirim.setText("Medan");
        } else if (textKotaPenerima.getText().equalsIgnoreCase("tanggerang")) {
            textProvinsiPenerima.setText("JAWA BARAT");
            textTujuanPengirim.setText("Tanggerang");
        } else if (textKotaPenerima.getText().equalsIgnoreCase("malang")) {
            textProvinsiPenerima.setText("JAWA TIMUR");
            textTujuanPengirim.setText("Malang");
        } else if (textKotaPenerima.getText().equalsIgnoreCase("semarang")) {
            textProvinsiPenerima.setText("JAWA TENGAH");
            textTujuanPengirim.setText("Semarang");
        } else if (textKotaPenerima.getText().equalsIgnoreCase("timika")) {
            textProvinsiPenerima.setText("PAPUA");
            textTujuanPengirim.setText("Timika");

        } else if (textKotaPenerima.getText().equalsIgnoreCase("")) {
            textProvinsiPenerima.setText("");
            textTujuanPengirim.setText("");

        } else {
            JOptionPane.showMessageDialog(textKodePosPenerima, "Kota Tidak Ditemukan Di System");
        }
    }

    public void setResultPengiriman() {
        textAreaDetailPembelian.setText("Nama Pengirim : " + pengirim.getNama() + "\n"
                + "Kota Tujuan : " + tarif.getKota() + "\n"
                + "Nama Barang : " + dpk.getNamaBarang() + "\n"
                + "Berat Barang : " + pengirim.getBeratBarang() + " KG" + "\n"
                + "Lama Pengiriman : " + dpk.getLamaPengiriman() + "\n"
                + "Jenis Pelayanan : " + dpk.getJenisLayanan() + "\n"
                + "Asuransi : " + insurance.getInsuranceCetak() + "\n"
                + "Tanggal Kirim : " + dateformat.format(dpk.getTanggalPengiriman()) + "\n"
                + "Pembayaran : " + dpk.getPembayaran());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TOP_PANEL;
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton buttonClear;
    private javax.swing.ButtonGroup buttonGroupAsuransi;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox<String> comboJenisBarang;
    private javax.swing.JComboBox<String> comboJenisLayanan;
    private javax.swing.JComboBox<String> comboPembayaran;
    private com.toedter.calendar.JDateChooser dateTanggalPengiriman;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelHargaBarang;
    private javax.swing.JLabel labelNamaBarang;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JMenuItem menuItemPrint;
    private javax.swing.JMenuItem menuItemResetMode;
    private javax.swing.JMenuItem menuItemSimulasiHarga;
    private javax.swing.JMenuItem menuItemThank;
    private javax.swing.JMenu menuNewDelivery;
    private javax.swing.JPanel panelDataPengiriman;
    private javax.swing.JPanel panelDetailPengiriman;
    private javax.swing.JRadioButton rbtnSetuju;
    private javax.swing.JRadioButton rbtnTidak;
    private javax.swing.JTextArea textAreaAlamatPenerima;
    private javax.swing.JTextArea textAreaAlamatPengirim;
    private javax.swing.JTextArea textAreaDetailPembelian;
    private javax.swing.JLabel textAsuransiPercent;
    private javax.swing.JTextField textBeratBarang1;
    private javax.swing.JTextField textDimensiLebar;
    private javax.swing.JTextField textDimensiPanjang;
    private javax.swing.JTextField textDimensiTinggi;
    private javax.swing.JTextField textHargaBarang;
    private javax.swing.JLabel textJumlah;
    private javax.swing.JTextField textKodePosPenerima;
    private javax.swing.JTextField textKodePosPengirim;
    private javax.swing.JTextField textKotaPenerima;
    private javax.swing.JTextField textKotaPengirim;
    private javax.swing.JTextField textNamaBarang;
    private javax.swing.JTextField textNamaPenerima;
    private javax.swing.JTextField textNamaPengirim;
    private javax.swing.JTextField textNomorPaket;
    private javax.swing.JTextField textProvinsiPenerima;
    private javax.swing.JTextField textProvinsiPengirim;
    private javax.swing.JTextField textTelephonePenerima;
    private javax.swing.JTextField textTelephonePengirim;
    private javax.swing.JTextField textTujuanPengirim;
    // End of variables declaration//GEN-END:variables
}
